print("Hello User")
print("Please give me a number. Any number")
x=int(input())
print(6+x)
print("You now have 6 plus that number")
print("Enter another number.")
y=int(input())
print(6*y)
print("You now have 6 times that number")
print("Give me a name")
name=input()
print(str(name) + str( 6+x) + str( 6*y))
print("You now have your name with your numbers, all in one neat bundle. Feel accomplished")